Repository icure/cardinal-sdk, pull requests merged in 2025-02, with the labels that each got.

#234 Updated models and APIs
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/raw/RawInvoiceApi.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/raw/impl/RawDocumentApiImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/raw/impl/RawInvoiceApiImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/CryptoActorStub.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/Invoice.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/Patient.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/base/CryptoActor.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/embed/InvoicingCode.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/security/ExternalJwtSelector.kt
Labels: automation

#238 Updated models and APIs
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/CryptoActorStub.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/Device.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/HealthcareParty.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/Patient.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/base/CryptoActor.kt
Labels: automation

#239 Updated models and APIs
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/raw/RawAnonymousApi.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/raw/impl/RawAnonymousApiImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/filters/CalendarItemFilters.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/CalendarItemType.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/filter/calendarItem/CalendarItemByDataOwnerUpdatedAfter.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/serialization/AbstractFilterSerializers.kt
  dart-wrapper/lib/build.gradle.kts
Labels: automation

#242 Updated models and APIs
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/filters/CalendarItemFilters.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/filter/calendarItem/CalendarItemByDataOwnerLifecycleBetween.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/serialization/AbstractFilterSerializers.kt
Labels: automation

#243 fix: Allow key sharing across iOS devices, check accessLevel to enforce user auth on Android
  cardinal-sdk/src/androidMain/kotlin/com/icure/cardinal/sdk/storage/SecureStorageFacade.android.kt
  cardinal-sdk/src/appleMain/kotlin/com/icure/cardinal/sdk/storage/SecureStorageFacade.apple.kt
Labels: bug, enhancement

#246 Updated models and APIs
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/Apis.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/CardinalBaseSdk.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/CardinalSdk.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/TimeTableApi.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/impl/TimeTableApiImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/raw/RawTimeTableApi.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/raw/impl/RawTimeTableApiImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/crypto/entities/EntityWithEncryptionMetadataTypeName.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/crypto/entities/EntityWithTypeInfo.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/filters/TimeTableFilters.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/TimeTable.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/filter/calendarItem/CalendarItemByDataOwnerLifecycleBetween.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/serialization/EncryptableSerializationModule.kt
Labels: automation

#247 Release 1.2.0
  cardinal-sdk/src/androidMain/kotlin/com/icure/cardinal/sdk/storage/SecureStorageFacade.android.kt
  cardinal-sdk/src/appleMain/kotlin/com/icure/cardinal/sdk/storage/SecureStorageFacade.apple.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/Apis.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/CardinalBaseSdk.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/CardinalSdk.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/TimeTableApi.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/impl/TimeTableApiImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/raw/RawTimeTableApi.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/raw/impl/RawTimeTableApiImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/crypto/entities/EntityWithEncryptionMetadataTypeName.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/crypto/entities/EntityWithTypeInfo.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/filters/CalendarItemFilters.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/filters/TimeTableFilters.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/TimeTable.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/filter/calendarItem/CalendarItemByDataOwnerLifecycleBetween.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/serialization/AbstractFilterSerializers.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/serialization/EncryptableSerializationModule.kt
Labels: enhancement

#254 Updated models and APIs
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/CardinalSdk.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/impl/DataOwnerApiImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/impl/ShamirKeysManagerApiImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/raw/impl/RawTimeTableApiImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/crypto/impl/BaseExchangeKeysManagerImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/crypto/impl/UserEncryptionKeysManagerImpl.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/CryptoActorStub.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/Device.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/ExchangeData.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/HealthcareParty.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/Patient.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/base/CryptoActor.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/model/extensions/CryptoActor.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/serialization/AbstractFilterSerializers.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/serialization/CryptoActorAsStubDeserializer.kt
Labels: automation

#261 Release 1.3.0
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/CalendarItemApi.kt
  cardinal-sdk/src/commonMain/kotlin/com/icure/cardinal/sdk/api/impl/CalendarItemApiImpl.kt
Labels: release
